const math = "/math";
const ca = "/classical_algebra/";
const calc = "/calculus/";
const phys = "/physics/";
const ra = "/real_analysis/";
const geo = "/geometry/";
const proba = "/probability/";
const lin = "/linear_algebra/";
const dm = "/discrete_mathematics/";
const num = "/number_theory/";
const sets = "/set_theory/";
const log = "/logic/";
const cs = "/cs";
const fs = "/foundations";
const fp = "/functional_programming";
const lp = "/logic_programming/";
const sml = "/sml/";
const dsa = "/data_structures_and_algorithms";
const asy = "/asynchronous_programming";
const ja = "/java/";
const swf = "swift/";
const sys = "/systems/";
const tls = "/tools/";
const shells = "shells/";
const git = "git/";
const lang = "/languages/";
const mob = "/mobile_systems/";
const da = "/dynamic_arrays/";
const str = "/strings/";
const ll = "/linked_lists/";
const cl = "/circular_lists/";
const dbl = "/doubly_linked_lists/";
const stack = "/stacks/";
const heap = "/heaps/";
const queue = "/queues/";
const ht = "/hashTables/";
const clang = "c/";

const Routes = [
	{ name: "Front Matter", path: "/" },
	{ name: "Notation Reference", path: "/notation" },
	{ name: "Algorithm Zoo", path: "/zoo/algorithms/main" },
	{ name: "Notes on Writing", path: "/writing" },
	{ name: "Review of Computer Science",
		path: `${cs}/preface`,
		children: [
			{ name: "Foundations with Java", path: `${cs}${fs}/preface`, children: [
				{ name: "Variables & Types", path: `${cs}${fs}${ja}variables_and_types` },
				{ name: "Conditionals", path: `${cs}${fs}${ja}conditionals` },
				{ name: "Variable Scope", path: `${cs}${fs}${ja}variable_scope` },
				{ name: "Arrays", path: `${cs}${fs}${ja}arrays` },
				{ name: "Loops", path: `${cs}${fs}${ja}loops` },
			]},
			{ name: "Functional Programming", path: `${cs}${fp}${sml}intro`, children: [
				{ name: "Simple Data Types", path: `${cs}${fp}${sml}simple_data_types` },
				{ name: "Compound Data Types", path: `${cs}${fp}${sml}compound_data_types` },
			]},
			{ name: "Logic Programming", path: `${cs}${lp}intro`, children: [
				{ name: "Horns", path: `${cs}${lp}basics` },
			]},
			{ name: "Asynchronous Programming with JavaScript", path: `${cs}${asy}/preface`, children: [
				{ name: "Fundamentals", path: `${cs}${asy}fundamentals` },
				{ name: "Control Flow", path: `${cs}${asy}control_flow` },
				{ name: "Arrays", path: `${cs}${asy}arrays` },
				{ name: "Object Literals", path: `${cs}${asy}object_literals` },
				{ name: "Keyword 'this'", path: `${cs}${asy}keyword_this` },
				{ name: "Functional Programming Techniques", path: `${cs}${asy}functional_programming` },
				{ name: "TypeScript", path: `${cs}${asy}typescript` },
			]},
			{ name: "Data Structures & Algorithms with C++", path: `${cs}${dsa}/intro`, children: [
				
					{ name: "Prelude: Data Structures & Algorithms", path: `${cs}${dsa}/dsa_overview`, },
					{ name: "Complexity Analysis", path: `${cs}${dsa}/dsa_complexity_analysis`, },
					{ name: "Numeric Algorithms", path: `${cs}${dsa}/dsa_numeric_algorithms`, },
					{ name: "Static Arrays", path: `${cs}${dsa}arrays`,
						children: [
							{ name: "Linear Search", path: `${cs}${dsa}arrays#linear-search`, },
							{ name: "Binary Search", path: `${cs}${dsa}arrays#binary-search`, },
							{ name: "Max Finder", path: `${cs}${dsa}arrays#max-finder` },
							{ name: "Min Finder", path: `${cs}${dsa}arrays#min-finder` },
							{ name: "Summation", path: `${cs}${dsa}arrays#summate` },
							{ name: "Arithmetic Mean", path: `${cs}${dsa}arrays#arithmetic-mean`, },
							{ name: "Reversal", path: `${cs}${dsa}arrays#reversal` },
							{ name: "Shifting Elements", path: `${cs}${dsa}arrays#shift` },
							{ name: "Rotating Elements", path: `${cs}${dsa}arrays#rotate`, },
							{ name: "Sorted Insertion", path: `${cs}${dsa}arrays#sorted-insert`, },
							{ name: "Is this Array Sorted?", path: `${cs}${dsa}arrays#sort-check`, },
							{ name: "Cost-benefit Analysis: Arrays", path: `${cs}${dsa}arrays#cost-benefit-analysis-arrays`, },
						],
					},
					{ name: "Dynamic Arrays", path: `${cs}${dsa}${da}dynamic_arrays` },
					{ name: "Strings", path: `${cs}${dsa}${str}strings` },
					{ name: "Time Algorithms", path: `${cs}${dsa}time`, },
					{ name: "Matrices", path: `${cs}${dsa}matrices` },
					{ name: "Linked Lists", path: `${cs}${dsa}${ll}linked_lists` },
					{ name: "Disjoint Sets", path: `${cs}${dsa}disjoint_sets` },
					{ name: "Circular Linked Lists", path: `${cs}${dsa}${cl}circular_linked_lists`, },
					{ name: "Doubly Linked Lists", path: `${cs}${dsa}${dbl}doubly_linked_lists`, },
					{ name: "Stacks", path: `${cs}${dsa}${stack}stacks` },
					{ name: "Queues", path: `${cs}${dsa}${queue}queues` },
					{ name: "Hash Tables", path: `${cs}${dsa}${ht}hash_tables` },
					{ name: "Trees", path: `${cs}${dsa}intro`, children: [
							{ name: "Binary Trees", path: `${cs}${dsa}binary_trees`, },
							{ name: "Tree Traversal", path: `${cs}${dsa}tree_traversal`,
								children: [
									{ name: "Preorder Traversal", path: `${cs}${dsa}preorder`, },
									{ name: "Inorder Traversal", path: `${cs}${dsa}inorder`, },
									{ name: "Postorder Traversal", path: `${cs}${dsa}postorder`, },
									{ name: "Breadth-first Traversal", path: `${cs}${dsa}breadth_first`, },
									{ name: "Comparing Traversal Methods", path: `${cs}${dsa}comparing_traversal_methods`, },
									{ name: "Traversal Sketching", path: `${cs}${dsa}traversal_sketching`, },
									{ name: "Traversal Complexities", path: `${cs}${dsa}traversal_complexities`, },
									{ name: "Traversal Generation", path: `${cs}${dsa}traversal_generation`, },
								],
							},
							{ name: "Order Determination", path: `${cs}${dsa}order_determination`, },
							{ name: "Tree Summation", path: `${cs}${dsa}tree_sum`, },
							{ name: "Binary Search Trees (BST)", path: `${cs}${dsa}binary_search_trees`,
								children: [
									{ name: "Searching BSTs", path: `${cs}${dsa}searching_binary_search_trees`, },
									{ name: "Inserting New Nodes", path: `${cs}${dsa}bst_insertion`, },
									{ name: "BST Constructor", path: `${cs}${dsa}bst_constructor`, },
									{ name: "Deleting Nodes", path: `${cs}${dsa}bst_node_deletion`, },
									{ name: "BST Traversal Generation", path: `${cs}${dsa}bst_traversal_generation`, },
									{ name: "BST Costs", path: `${cs}${dsa}bst_costs`, },
								],
							},
							{ name: "AVL Trees", path: `${cs}${dsa}avl_trees`, children: [
								{ name: "Rotations", path: `${cs}${dsa}avl_trees#rotations`},
								{ name: "Right-rotation", path: `${cs}${dsa}avl_trees#right-rotation`},
								{ name: "Left-rotation", path: `${cs}${dsa}avl_trees#left-rotation`},
								{ name: "Right-left-rotation", path: `${cs}${dsa}avl_trees#right-left-rotation`},
								{ name: "Left-left-rotation", path: `${cs}${dsa}avl_trees#left-left-rotation`},
								{ name: "General Form of AVL Rotations", path: `${cs}${dsa}avl_trees#general-form-of-avl-rotations`},

							]},
							{ name: "B-trees", path: `${cs}${dsa}btrees` },
							{ name: "Red-black Trees", path: `${cs}${dsa}red_black_trees` },
							{ name: "Fenwick Trees", path: `${cs}${dsa}fenwick_trees` },
						],
					},
					{ name: "Heaps", path: `${cs}${dsa}${heap}heaps` },
					{ name: "Sorting Algorithms", path: `${cs}${dsa}/sorting` },
					{ name: "Recursion", path: `${cs}${dsa}/recursion` },
					{ name: "Backtracking", path: `${cs}${dsa}/backtracking` },
					{ name: "Common Problems", path: `${cs}${dsa}/commons` },
					{ name: "Summary", path: `${cs}${dsa}/dsa_summary` },
				],
			},
			{ name: "Computer Systems", path: `${cs}${sys}intro`, children: [
					{ name: "Language Overview: C", path: `${cs}${sys}${clang}c_basics` },
					{ name: "Pointers", path: `${cs}${sys}pointers` },
					{ name: "Digital Signals", path: `${cs}${sys}digital_signals` },
					{ name: "Binary Representation", path: `${cs}${sys}binary_representation` },
					{ name: "Floating Point Numbers", path: `${cs}${sys}floats` },
					{ name: "Boolean Logic", path: `${cs}${sys}boolean_logic` },
					{ name: "Logic Gates", path: `${cs}${sys}logic_gates` },
					{ name: "The ALU", path: `${cs}${sys}alu` },
					{ name: "Implementing Time", path: `${cs}${sys}time` },
					{ name: "Memory", path: `${cs}${sys}memory` },
					{ name: "RAM", path: `${cs}${sys}ram` },
					{ name: "PC", path: `${cs}${sys}pc` },
					{ name: "Machine Language", path: `${cs}${sys}machine_language` },
					{ name: "Memory Hierarchy", path: `${cs}${sys}memory_hierarchy` },
					{ name: "Memory in x86-64", path: `${cs}${sys}x86_memory` },
					{ name: "The CPU", path: `${cs}${sys}cpu` },
					{ name: "Assemblers", path: `${cs}${sys}assemblers`, children: [
						{ name: "x86 Assembly", path: `${cs}${sys}x86_assembly` },
					]},
					{ name: "Virtual Machines", path: `${cs}${sys}virtual_machines`, children: [
						{ name: "Implementing a Virtual Machine", path: `${cs}${sys}vm_implementation` },
					]},
					{ name: "Compilers", path: `${cs}${sys}compilers` },
					{ name: "Code Optimization", path: `${cs}${sys}code_optimization` },
					{ name: "Linkers", path: `${cs}${sys}linkers` },
					{ name: "Interrupts", path: `${cs}${sys}interrupts` },
					{ name: "Computer Networks", path: `${cs}${sys}networks`, children: [
						{ name: "Overview", path: `${cs}${sys}client_server` },
						{ name: "Application Layer", path: `${cs}${sys}application_layer`, children:[
							{ name: "Web Applications", path: `${cs}${sys}web_applications` },
						]},
						{ name: "Data Layer", path: `${cs}${sys}data_layer` },
						// { name: "The Internet & ISPs", path: `${cs}${sys}isp` },
					]},
				],
			},
			{ name: "Mobile Systems", path: `${cs}${mob}preface`, children: [
				{ name: "MVVM", path: `${cs}${mob}mvvm` },
				{ name: "Swift", path: `${cs}${mob}${swf}intro`, children: []},
			] },
			{ name: "Computer Languages", path: `${cs}${lang}preface`, children: [
				{ name: "Introduction to Parsing", path: `${cs}${lang}intro_to_parsing` },
			]},
			{ name: "Tools", path: `${cs}${tls}intro`, children: [
				{ name: "Bash", path: `${cs}${tls}${shells}basics` },
				{ name: "Git", path: `${cs}${tls}${git}basics` },
				{ name: "C++", path: `${cs}${tls}cpp_overview` },
				{ name: "Build Systems", path: `${cs}${tls}build_systems` },
				{ name: "Time Complexities", path: `${cs}${tls}time_complexities` },
				{ name: "Language: C++", path: `${cs}${dsa}/language_overview_cpp`, children: [
					{ name: "Errors", path: `${cs}${dsa}errors` },
					{ name: "Operators", path: `${cs}${dsa}operators` },
					{ name: "Variables & Types", path: `${cs}${dsa}variables_and_types`, },
					{ name: "Header Files", path: `${cs}${dsa}header_files` },
					{ name: "Overflow", path: `${cs}${dsa}overflow` },
					{ name: "Value v. Reference Semantics", path: `${cs}${dsa}value_reference_semantics`, },
					{ name: "Strings", path: `${cs}${dsa}cpp-strings` },
					{ name: "Functions", path: `${cs}${dsa}functions`, children: [
							{ name: "Function Overloading", path: `${cs}${dsa}function_overloading`, },
							{ name: "Function Templates", path: `${cs}${dsa}function_templates`, },
							{ name: "Argument Passing", path: `${cs}${dsa}argument_passing`, },
							{ name: "Function Returns", path: `${cs}${dsa}function_returns`, },
							{ name: "Variable Scope", path: `${cs}${dsa}variable_scope`, },
							{ name: "Static Variables", path: `${cs}${dsa}static_variables`, },
							{ name: "Recursion Generally", path: `${cs}${dsa}cpp-recursion`, },
						],
					},
					{ name: "Preprocessing", path: `${cs}${dsa}preprocessing`, },
					{ name: "Libraries", path: `${cs}${dsa}libraries` },
					{ name: "I/O Streams", path: `${cs}${dsa}io_streams` },
					{ name: "Namespaces", path: `${cs}${dsa}namespaces` },
					{ name: "Collections", path: `${cs}${dsa}collections` },
					{ name: "Pointers", path: `${cs}${dsa}pointers` },
					{ name: "Classes", path: `${cs}${dsa}classes` },
					{ name: "Friend Functions", path: `${cs}${dsa}friend_functions`, },
					{ name: "Metaprogramming: Templates", path: `${cs}${dsa}templates`, },
				],
			},
				// { name: "Makefiles", path: `${cs}${tls}/make` },
			]},
		],
	},
	{ name: "Review of Mathematics", path: `${math}/preface`,children: [
			{ name: "Reference", path: `${math}/reference` },
			{ name: "Set Theory", path: `${math}${sets}axioms`, children: [
				{ name: "Naive Set Theory", path: `${math}${sets}axioms`},
				{ name: "Tuples", path: `${math}${sets}tuples`},
				{ name: "Relations", path: `${math}${sets}relations`, children: [
					{ name: "Binary Relations", path: `${math}${sets}relations#binary-relations` },
					{ name: "Relations Generally", path: `${math}${sets}relations#relations-generally` },
					{ name: "Language of Relations", path: `${math}${sets}relations#relation-language` },
					{ name: "Homogenous Relations", path: `${math}${sets}relations#homogenous-relations` },
					{ name: "Heterogenous Relations", path: `${math}${sets}relations#heterogenous-relations` },
					{ name: "The Empty Relation", path: `${math}${sets}relations#types-of-relations` },
					{ name: "Reflexive Relations", path: `${math}${sets}relations#reflexive-relations` },
					{ name: "Irreflexive Relations", path: `${math}${sets}relations#irreflexive-relations` },
					{ name: "Quasi-reflexive Relations", path: `${math}${sets}relations#quasi-reflexive-relations` },
					{ name: "Symmetric Relations", path: `${math}${sets}relations#symmetric-relations` },
					{ name: "Antiymmetric Relations", path: `${math}${sets}relations#antisymmetric-relations` },
					{ name: "Asymmetric Relations", path: `${math}${sets}relations#asymmetric-relations` },
					{ name: "Transitive Relations", path: `${math}${sets}relations#transitive-relations` },
					{ name: "Intransitive Relations", path: `${math}${sets}relations#intransitive-relations` },
					{ name: "Left-total Relations", path: `${math}${sets}relations#left-total-relations` },
					{ name: "Right-total Relations", path: `${math}${sets}relations#right-total-relations` },
					{ name: "Comparable Relations", path: `${math}${sets}relations#comparable-relations` },
					{ name: "Connex Relations", path: `${math}${sets}relations#connex-relations` },
					{ name: "Incomparable Relations", path: `${math}${sets}relations#incomparable-relations` },
					{ name: "Right Euclidean Relations", path: `${math}${sets}relations#right-euclidean-relation` },
					{ name: "Left Euclidean Relations", path: `${math}${sets}relations#left-euclidean-relation` },
					{ name: "Equivalence Relations", path: `${math}${sets}relations#equivalence-relations` },
					{ name: "Partial Orders", path: `${math}${sets}relations#partial-orders` },
					{ name: "Weak Partial Orders", path: `${math}${sets}relations#weak-partial-orders` },
					{ name: "Strong Partial Orders", path: `${math}${sets}relations#strong-partial-orders` },
					{ name: "Total Orders", path: `${math}${sets}relations#total-order` },
					{ name: "Preorders", path: `${math}${sets}relations#preorders` },
					{ name: "Posets", path: `${math}${sets}relations#posets` },
					{ name: "Minimals and Maximals", path: `${math}${sets}relations#minimal-and-maximal-elements` },
					{ name: "Chains", path: `${math}${sets}relations#chains` },
					{ name: "Lower and Upper Bounds", path: `${math}${sets}relations#lower-bound-and-upper-bound` },
					{ name: "Infimum and Supremum", path: `${math}${sets}relations#infimum-and-supremum` },
					{ name: "Minimum and Maximum", path: `${math}${sets}relations#mimimum-and-maximum` },
					{ name: "Well-orderings", path: `${math}${sets}relations#well-ordered-relations` },
					{ name: "Left-unique Relations", path: `${math}${sets}relations#left-unique-relations` },
					{ name: "Right-unique Relations", path: `${math}${sets}relations#right-unique-relations` },
					{ name: "Maps", path: `${math}${sets}relations#maps` },
					{ name: "Functions", path: `${math}${sets}relations#functions` },
					{ name: "Restrictions and Extensions", path: `${math}${sets}relations#restrictions-and-extensions` },
					{ name: "Partial Orders of Functions", path: `${math}${sets}relations#partial-orders-of-functions` },
					{ name: "Surjections", path: `${math}${sets}relations#surjections` },
					{ name: "Injections", path: `${math}${sets}relations#injections` },
					{ name: "Bijections", path: `${math}${sets}relations#bijections` },
					{ name: "Surjection Rule", path: `${math}${sets}relations#the-surjection-rule` },
					{ name: "Injection Rule", path: `${math}${sets}relations#the-injection-rule` },
					{ name: "Bijection Rule", path: `${math}${sets}relations#the-bijection-rule` },
					{ name: "Families", path: `${math}${sets}relations#families` },
					{ name: "Constructing the Natural Numbers", path: `${math}${sets}relations#natural-numbers` },
					{ name: "Axiom of Infinity", path: `${math}${sets}relations#the-axiom-of-infinity` },
					{ name: "Peano Axioms", path: `${math}${sets}relations#peano-axioms` },
					{ name: "Sequences", path: `${math}${sets}relations#sequences` },
					{ name: "Equivalence Class", path: `${math}${sets}relations#equivalence-class` },
				]},
				{ name: "Alebraic Structures", path: `${math}${sets}operations`},
				{ name: "Classes", path: `${math}${sets}class`},
			]},
			{ name: "Mathematical Logic", path: `${math}${log}preface`, children: [
				
				{ name: "Language", path: `${math}${log}language` },
				{ name: "Propositional Logic", path: `${math}${log}propositional-logic` },
				{ name: "Predicate Logic", path: `${math}${log}predicate-logic` },
				// { name: "Arguments", path: `${math}${log}arguments` },
			]},
			{ name: "Classical Algebra", path: `${math}${ca}intro`, children: [
					{ name: "Addition", path: `${math}${ca}addition` },
					{ name: "Closure", path: `${math}${ca}closure` },
					{ name: "Distributivity", path: `${math}${ca}distributivity` },
					{ name: "Division & Divisibility", path: `${math}${ca}division_and_divisibility`, },
					{ name: "Proportions", path: `${math}${ca}proportions`, },
					{ name: "Rational Expressions", path: `${math}${ca}rational_expressions`, },
					{ name: "Expansions", path: `${math}${ca}expansions` },
					{ name: "Exponentiation", path: `${math}${ca}exponentiation` },
					{ name: "Inequalities", path: `${math}${ca}inequalities` },
					{ name: "Absolute Value", path: `${math}${ca}absolute_value` },
					{ name: "Multiplication", path: `${math}${ca}multiplication` },
					{ name: "Multivariable Relationships", path: `${math}${ca}multivariable_relationships`, },
					{ name: "Number Sets", path: `${math}${ca}number_sets` },
					{ name: "Perfect Powers", path: `${math}${ca}perfect_powers` },
					{ name: "Radicals", path: `${math}${ca}radicals` },
					{ name: "Order of Operations", path: `${math}${ca}order_of_operations`, },
					{ name: "Logarithms", path: `${math}${ca}logarithms` },
					{ name: "Rational Numbers", path: `${math}${ca}rational_numbers`, },
					{ name: "Irrational Numbers", path: `${math}${ca}irrational_numbers`, },
					{ name: "Imaginary Numbers", path: `${math}${ca}imaginary_numbers`, },
					{ name: "Decimal System", path: `${math}${ca}decimal_system` },
					{ name: "Real Numbers", path: `${math}${ca}real_numbers` },
					{ name: "Expressions", path: `${math}${ca}expressions` },
					{ name: "Equation Families", path: `${math}${ca}equation_families`, },
					{ name: "Truth Sets & Sentences", path: `${math}${ca}truth_sets` },
					{ name: "Conditional Equations", path: `${math}${ca}conditional_equations`, },
					{ name: "Linear Equations in One Variable", path: `${math}${ca}linear_equations_1_variable`, },
					{ name: "Expression Domain", path: `${math}${ca}expression_domain`, },
					{ name: "Polynomial Equations", path: `${math}${ca}polynomial_equations`, },
					{ name: "Inequations", path: `${math}${ca}inequations` },
					{ name: "Quadratics", path: `${math}${ca}quadratics` },
					{ name: "Solving Quadratics", path: `${math}${ca}solving_quadratics`, },
					{ name: "Binomial Theorem", path: `${math}${ca}binomial_theorem`, },
					{ name: "Matrices", path: `${math}${ca}matrices`, },
				],
			},
			// { name: "Abstract Algebra", path: `${math}${aba}intro`, children: []},
			{ name: "Geometry", path: `${math}${geo}foundations`, children: [
				{ name: "Trigonometry", path: `${math}${geo}trigonometry` }
			]},
			{ name: "Linear Algebra", path: `${math}${lin}intro`, children: [
				{ name: "Gaussian Elimination", path: `${math}${lin}gaussian-elimination` },
				{ name: "Vector Algebra", path: `${math}${lin}vectors` },
			]},
			{ name: "Probability Theory", path: `${math}${proba}axioms`, children: [
				{ name: "Axioms", path: `${math}${proba}axioms`},
				{ name: "Conditional Probability", path: `${math}${proba}conditioning` },
			]},
			{ name: "Number Theory", path: `${math}${num}preface`, children: [
				{ name: "Divisibility", path: `${math}${num}divisibility`},
			] },
			{ name: "Real Analysis", path: `${math}${ra}preface`, children: [
				{ name: "Rational Construction", path: `${math}${ra}rationals` },
			] },
			{ name: "Discrete Mathematics", path: `${math}${dm}preface`, children: [
				{ name: "Induction", path: `${math}${dm}induction` },
				{ name: "Invariants", path: `${math}${dm}invariants` },
				{ name: "Strong Induction", path: `${math}${dm}strong_induction` },
				{ name: "Number Theory", path: `${math}${dm}number_theory`},
				// { name: "Set Theory", path: `${math}${dm}set_theory` },
				{ name: "Relations", path: `${math}${dm}relations` },
				{ name: "Functions", path: `${math}${dm}functions` },
				{ name: "Graph Theory", path: `${math}${dm}graph_theory` },
				{ name: "Combinatorics", path: `${math}${dm}combinatorics` },
				{ name: "Sequences & Sums", path: `${math}${dm}sums` },
			]},
			{ name: "Calculus", path: `${math}${calc}preface`, children: [
				{ name: "Intervals", path: `${math}${calc}intervals` },
				{ name: "The Cartesian Plane", path: `${math}${calc}cartesian_plane` },
				{ name: "The Distance Formula", path: `${math}${calc}distance_formula` },
				{ name: "Slope", path: `${math}${calc}slope` },
				{ name: "Functions", path: `${math}${calc}functions` },
				{ name: "Functions & Graphs", path: `${math}${calc}function_graphs` },
				{ name: "The Absolute Value Function", path: `${math}${calc}absolute_value_function` },
				{ name: "Exponential Functions", path: `${math}${calc}exponential_functions` },
				{ name: "Logarithmic Functions", path: `${math}${calc}logarithmic_functions` },
				{ name: "Quadratic Functions", path: `${math}${calc}quadratic_functions` },
				{ name: "Periodic Functions", path: `${math}${calc}trig_functions` },
				{ name: "The Derivative", path: `${math}${calc}derivative` },
				{ name: "Limits", path: `${math}${calc}limits` },
				{ name: "Derivatives of Trigonometric Functions", path: `${math}${calc}trig_derivatives` },
				{ name: "Derivative Manipulation", path: `${math}${calc}derivative_manipulation` },
				{ name: "Implicit Differentiation", path: `${math}${calc}implicit_differentiation` },
				{ name: "Derivatives of Exponential & Logarithmic Functions", path: `${math}${calc}exponential_and_logarithmic_derivatives` },
				{ name: "Linear Approximations", path: `${math}${calc}linear_approximations` },
				{ name: "Quadratic Approximations", path: `${math}${calc}quadratic_approximations` },
				{ name: "Curve Sketching", path: `${math}${calc}curve_sketching` },
				{ name: "Maxima & Minima", path: `${math}${calc}maxima_and_minima` },
				{ name: "Related Rates", path: `${math}${calc}related_rates` },
				{ name: "Newton's Method", path: `${math}${calc}newtons_method` },
				{ name: "The Mean Value Theorem", path: `${math}${calc}mean_value_theorem` },
				{ name: "Introduction to Integration", path: `${math}${calc}introduction_to_integration` },
				{ name: "Definite Integrals", path: `${math}${calc}definite_integrals` },
				{ name: "𝑢-Substitution", path: `${math}${calc}u_substitution` },
				{ name: "Riemann Sums", path: `${math}${calc}riemann_sums` },
				{ name: "The Fundamental Theorem of Calculus", path: `${math}${calc}ftc` },
				{ name: "Common Applications of Integrals", path: `${math}${calc}integral_applications` },
				{ name: "Areas Between Curves", path: `${math}${calc}areas_between_curves` },
				{ name: "Techniques of Integration", path: `${math}${calc}integration_techniques` },
				{ name: "Series", path: `${math}${calc}series` },
			]},
			{ name: "Applied Mathematics", path: `${math}${phys}mechanics`, children: [
				{ name: "Mechanics", path: `${math}${phys}mechanics` },
			]},
			// { name: "Statistics", path: `${math}${stat}preface`, children: [
				// { name: "Foundational Definitions", path: `${math}${stat}foundational_definitions` },
			// ]},
		],
	},
];

export default Routes;
